spring:
  datasource:
    url: jdbc:mysql://localhost/springangularscaffold?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
custom-app-config:
  cookies:
    secure: false
  cors:
    allowed-origins:
      - http://localhost:4200
storage:
  aws:
    credentials:
      access-key: minioadmin
      secret-key: minioadmin
    s3:
      endpoint: http://localhost:9000
      region:
      public-resource: "arn:aws:s3:::springangularscaffold/public/*"
