spring:
  datasource:
    url: jdbc:mysql://eu-cdbr-west-01.cleardb.com/heroku_d711b68265c57f6?reconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: bffa0f0eaa51d1
    password: 1fce9207
custom-app-config:
  cors:
    allowed-origins:
      - https://springangularscaffold.herokuapp.com

storage:
  aws:
    credentials:
      access-key:
      secret-key:
    s3:
      endpoint: s3.nl-ams.scw.cloud
      region: nl-ams
      public-resource: "springangularscaffold/public/*"
